[package]
name = "regex"
version = "2.7.1"
description = "Motoko regex engine for pattern matching on the Internet Computer."
repository = "https://github.com/Demali-876/motoko_regex_engine"
keywords = [ "regex", "pattern", "matching", "search" ]
license = "MIT"

[toolchain]
moc = "0.13.2"
wasmtime = "26.0.0"
pocket-ic = "4.0.0"

[dependencies]
base = "0.13.3"